language: ru

database-type: H2
mysql:
  host: "localhost"
  port: 3306
  user: "root"
  password: ""

text-formatting:
  parser-type: MINIMESSAGE
  enable-alignment: true

passport-gui: example-rp

give-suggestions:
  birthday: "Birthday"
  city: "City"
  sex: "Sex"
  value1: "Discord"
  value2: ""
  value3: ""
  value4: ""
  value5: ""
  value6: ""
  value7: ""
  value8: ""
  value9: ""
  value10: ""

view-radius: 10